// AUTO-GENERATED from supplier CP List (21-Aug-2026). Do not hand-edit rows;
// re-run the generator script against an updated price list instead.

export type SeedVariant = { size: string };
export type SeedProduct = { name: string; category: string; variants?: SeedVariant[] };

export const SEED_CATEGORIES: string[] = [
  'CD70 Euro 2',
  'CD70F',
  'CD70 CDI',
  'CG125',
  'CG125 CDI',
  'CG125 Euro 2',
  'CD100',
  'Qingqi 4-Stroke',
  'Star',
  'Hero',
  'LF70',
  'Sohrab',
  'United 100',
  'CG125 Deluxe',
  'C50 Z2',
  'JH90',
  'C100',
  'Universal / Generic Parts',
];

export const SEED_PRODUCTS: SeedProduct[] = [
  { name: 'AIR FILTER', category: 'CD70 Euro 2' },
  { name: 'AIR FILTER', category: 'CD70F' },
  { name: 'AIR FILTER BOTTLE (HOSE PIPE) 16MM', category: 'CD70 CDI' },
  { name: 'AIR FILTER FOAM', category: 'CG125' },
  { name: 'AIR LOTA', category: 'CD70 CDI' },
  { name: 'AIR LOTA', category: 'CD70 Euro 2' },
  { name: 'AXLE CENTER WITH NUT', category: 'CD70 CDI' },
  { name: 'AXLE FRONT WITH NUT', category: 'CD70 CDI' },
  { name: 'AXLE REAR WITH NUT', category: 'CD70 CDI' },
  { name: 'BACK LIGHT COMPLETE', category: 'CG125' },
  { name: 'BACK LIGHT COMPLETE (2003 MODEL)', category: 'CD70 CDI' },
  { name: 'BACK LIGHT HOLDER', category: 'CD70F' },
  { name: 'BACK LIGHT LENS', category: 'CG125' },
  { name: 'BACK TAKE (CHROME)', category: 'CD70 Euro 2' },
  { name: 'BACK VIEW MIRROR (BALL FUNCTION) SET', category: 'CD70 CDI' },
  { name: 'BALANCER', category: 'CG125' },
  { name: 'BRAKE CABLE', category: 'CD70 CDI' },
  { name: 'BRAKE CABLE (6MM)', category: 'CD70 Euro 2' },
  { name: 'BRAKE CABLE (JAPANESE STYLE)', category: 'CD70 CDI' },
  { name: 'BRAKE CABLE 2007 MODEL', category: 'CG125 CDI' },
  { name: 'BRAKE CABLE 2010 MODEL', category: 'CD70 Euro 2' },
  { name: 'BRAKE CABLE 2012 MODEL', category: 'CG125 Euro 2' },
  { name: 'BRAKE CAM LEVER & SHAFT FRONT', category: 'CD70F' },
  { name: 'BRAKE CAM LEVER & SHAFT REAR', category: 'CD70F' },
  { name: 'BRAKE PEDAL', category: 'CD70F' },
  { name: 'BRAKE PEDAL', category: 'CG125' },
  { name: 'BRAKE PEDAL SPRING', category: 'CD70F' },
  { name: 'BRAKE ROD', category: 'CD70 CDI' },
  { name: 'BRAKE SHOE PLATE ONLY FRONT', category: 'CD70F' },
  { name: 'BRAKE SHOE PLATE ONLY REAR', category: 'CD70F' },
  { name: 'BRAKE SHOE SET FRONT W/SPRING', category: 'CD100' },
  { name: 'BRAKE SHOE SET WITH BIG SPRING NON-ASBESTOS', category: 'CD70 Euro 2' },
  { name: 'BRAKE SHOE SET WITH SPRING', category: 'CD70F' },
  { name: 'BRAKE SHOE SET WITH SPRING', category: 'Qingqi 4-Stroke' },
  { name: 'BRAKE SHOE SET WITH SPRING EXTRA GRIP', category: 'CD70F' },
  { name: 'BRAKE SWITCH FRONT', category: 'CD70F' },
  { name: 'BRAKE SWITCH REAR W/SPRING', category: 'CD70F' },
  { name: 'C.D.I UNIT LEED', category: 'CD70 CDI' },
  { name: 'C.D.I UNIT LEED (MB100)', category: 'Star' },
  { name: 'C.D.I. STARTING COIL (GUTKA COIL)', category: 'CD70 CDI' },
  { name: 'C.D.I. STARTING COIL (GUTKA COIL)', category: 'Hero' },
  { name: 'C.D.I. STARTING COIL (GUTKA COIL) HEAVY DUTY COMMON WITH CD70-CDI', category: 'CG125 CDI' },
  { name: 'C.D.I. UNIT', category: 'CD70F' },
  { name: 'C.D.I. UNIT', category: 'CG125 CDI' },
  { name: 'C.D.I. UNIT (ELECTRIC START)(4 PIN)', category: 'LF70' },
  { name: 'C.D.I. UNIT (MB100)', category: 'Star' },
  { name: 'C.D.I. UNIT (MB100) (PREMIUM QUALITY)', category: 'Star' },
  { name: 'CAM FOLLOWER', category: 'CG125' },
  { name: 'CAM FOLLOWER', category: 'CG125 Euro 2' },
  { name: 'CAM GEAR SET', category: 'CG125' },
  { name: 'CAM GEAR SET (EURO II)', category: 'CG125 Euro 2' },
  { name: 'CAM GEAR SET HEAVY DUTY', category: 'CG125' },
  { name: 'CAM PIN ROCKER ORING', category: 'CG125' },
  { name: 'CAM SHAFT', category: 'CD100' },
  { name: 'CAM SHAFT', category: 'CD70 CDI' },
  { name: 'CAM SHAFT', category: 'Sohrab' },
  { name: 'CAM SHAFT (2012 MODEL)', category: 'CD70 Euro 2' },
  { name: 'CAM SHAFT (ALTER)', category: 'Star' },
  { name: 'CARBURETOR (PZ-16) 72CC', category: 'CD70 CDI' },
  { name: 'CARBURETOR (PZ-16) 78CC', category: 'CD70F' },
  { name: 'CARBURETOR (PZ-18)', category: 'CD70 Euro 2' },
  { name: 'CARBURETOR (PZ-22)', category: 'United 100' },
  { name: 'CARBURETOR (PZ-26 SD)', category: 'CG125 Euro 2' },
  { name: 'CARBURETOR (PZ-26)', category: 'CG125 CDI' },
  { name: 'CARBURETOR BEND (BIG HOLE)', category: 'CD70F' },
  { name: 'CARBURETOR BEND (EURO 11)', category: 'CD70 Euro 2' },
  { name: 'CARBURETOR BEND (SMALL HOLE)', category: 'CD70F' },
  { name: 'CARBURETOR CHOKE KIT', category: 'CD70 Euro 2' },
  { name: 'CARBURETOR CHOKE KIT', category: 'CD70F' },
  { name: 'CARBURETOR CHOKE KIT COMPLETE', category: 'CD70 Euro 2' },
  { name: 'CARBURETOR CHOKE KIT COMPLETE', category: 'CG125 CDI' },
  { name: 'CARBURETOR PISTON W/SPRING', category: 'CD70 Euro 2' },
  { name: 'CARBURETOR PISTON W/SPRING', category: 'CD70F' },
  { name: 'CARBURETOR PISTON W/SPRING', category: 'CG125 CDI' },
  { name: 'CARBURETOR PISTON W/SPRING', category: 'CG125 Euro 2' },
  { name: 'CHAIN COVER BOLT KIT', category: 'CD70 CDI' },
  { name: 'CHAIN COVER SET (SILVER)', category: 'CD70 CDI' },
  { name: 'CHAIN COVER SET (SILVER)', category: 'CG125' },
  { name: 'CHAIN KIT (38X15+420X104L) MODIFIED', category: 'CD70F' },
  { name: 'CHAIN KIT (38X15+428X100L)', category: 'CG125' },
  { name: 'CHAIN KIT (38X15+428X102L)', category: 'United 100' },
  { name: 'CHAIN KIT (38X15+428X102L) 3WHEELER', category: 'United 100' },
  { name: 'CHAIN KIT (41X14+420X104L) JAPANESE STYLE', category: 'CD70 CDI' },
  { name: 'CHAIN KIT (43X14+428HX110L)', category: 'CG125 Deluxe' },
  { name: 'CHAIN KIT (43X14+428X108L)', category: 'CD100' },
  { name: 'CHAIN SETTING LARGE', category: 'CD70 CDI' },
  { name: 'CHAIN SETTING SMALL', category: 'CD70 CDI' },
  { name: 'CLUTCH BOSS', category: 'CD100' },
  { name: 'CLUTCH BOSS', category: 'CD70F' },
  { name: 'CLUTCH BOSS', category: 'CG125 CDI' },
  { name: 'CLUTCH BOSS', category: 'CG125 Euro 2' },
  { name: 'CLUTCH BOSS', category: 'Qingqi 4-Stroke' },
  { name: 'CLUTCH BOSS', category: 'United 100' },
  { name: 'CLUTCH BOSS SPRING', category: 'CD70F' },
  { name: 'CLUTCH BOSS SPRING', category: 'CG125' },
  { name: 'CLUTCH BOX ASSY. COMP', category: 'Qingqi 4-Stroke' },
  { name: 'CLUTCH BOX ASSY. COMP', category: 'United 100' },
  { name: 'CLUTCH BOX ASSY. COMP. W/GEAR', category: 'C50 Z2' },
  { name: 'CLUTCH BOX ASSY. COMP. W/GEAR', category: 'CD70F' },
  { name: 'CLUTCH BOX ASSY. COMP. W/GEAR', category: 'CG125 CDI' },
  { name: 'CLUTCH BOX W/GEAR', category: 'CG125' },
  { name: 'CLUTCH BUSH', category: 'CD70F' },
  { name: 'CLUTCH BUSH', category: 'United 100' },
  { name: 'CLUTCH CABLE', category: 'CD70 CDI' },
  { name: 'CLUTCH CABLE', category: 'CG125 CDI' },
  { name: 'CLUTCH CABLE 2010 MODEL', category: 'CD70 Euro 2' },
  { name: 'CLUTCH CABLE 2012 MODEL', category: 'CG125 Euro 2' },
  { name: 'CLUTCH CENTER KARA', category: 'CD70F' },
  { name: 'CLUTCH CENTER KARA', category: 'Qingqi 4-Stroke' },
  { name: 'CLUTCH COVER', category: 'CD70 CDI' },
  { name: 'CLUTCH GEAR', category: 'CD70F' },
  { name: 'CLUTCH GEAR', category: 'CG125' },
  { name: 'CLUTCH GEAR', category: 'United 100' },
  { name: 'CLUTCH GEAR 20T', category: 'Qingqi 4-Stroke' },
  { name: 'CLUTCH GEAR 65T', category: 'Qingqi 4-Stroke' },
  { name: 'CLUTCH GEAR BIG 67T', category: 'CD70F' },
  { name: 'CLUTCH GEAR HEAVY DUTY', category: 'CG125' },
  { name: 'CLUTCH HOUSING ASSEMBLY', category: 'CG125' },
  { name: 'CLUTCH HOUSING SET', category: 'CD100' },
  { name: 'CLUTCH HOUSING SET', category: 'CG125' },
  { name: 'CLUTCH HOUSING SET W/STEEL (DOTTED)', category: 'CG125' },
  { name: 'CLUTCH LIFTER (CROME)', category: 'CD70F' },
  { name: 'CLUTCH LIFTER (CROME)', category: 'CG125 CDI' },
  { name: 'CLUTCH LIFTER (CROME) (QINGQI-4ST)', category: 'United 100' },
  { name: 'CLUTCH LIFTER OVER SIZE', category: 'CD70F' },
  { name: 'CLUTCH LIFTER SPRING', category: 'CD70F' },
  { name: 'CLUTCH NUT LOCK SET', category: 'CD70F' },
  { name: 'CLUTCH NUT LOCK WITH OUTSIDE WASHER', category: 'CD70F' },
  { name: 'CLUTCH OUTER COVER', category: 'CD70F' },
  { name: 'CLUTCH PACKING (GREEN)', category: 'CD70F' },
  { name: 'CLUTCH PACKING (GREEN)', category: 'CG125' },
  { name: 'CLUTCH PATTI SET', category: 'CD70F' },
  { name: 'CLUTCH PLATE', category: 'CD70F' },
  { name: 'CLUTCH PLATE', category: 'CG125' },
  { name: 'CLUTCH PLATE', category: 'Qingqi 4-Stroke' },
  { name: 'CLUTCH PLATE', category: 'United 100' },
  { name: 'CLUTCH PLATE (PAPER TYPE)', category: 'CD70 Euro 2' },
  { name: 'CLUTCH PLATE (PAPER TYPE)', category: 'CG125 CDI' },
  { name: 'CLUTCH PUSHER', category: 'CD70F' },
  { name: 'CLUTCH WIRE', category: 'CD70F' },
  { name: 'CONNECTING ROD KIT', category: 'CD70F' },
  { name: 'CONNECTING ROD KIT', category: 'CG125' },
  { name: 'CONNECTING ROD KIT', category: 'Qingqi 4-Stroke' },
  { name: 'CONNECTING ROD KIT', category: 'Sohrab' },
  { name: 'CONNECTING ROD KIT', category: 'Star' },
  { name: 'COUNTER SHAFT', category: 'CD70 CDI' },
  { name: 'COUNTER SHAFT', category: 'United 100' },
  { name: 'CRANK SHAFT COMP. W/BEARING', category: 'CD70 CDI' },
  { name: 'CRANK SHAFT COMP. W/BEARING', category: 'CD70 Euro 2' },
  { name: 'CRANK SHAFT COMP. W/BEARING', category: 'Star' },
  { name: 'CUSHION RUBBER SET', category: 'CD70F' },
  { name: 'CUSHION RUBBER SET', category: 'CG125' },
  { name: 'CUSHION SET FRONT', category: 'CD70 CDI' },
  { name: 'CUSHION SET FRONT', category: 'CG125 CDI' },
  { name: 'CUSHION SET FRONT', category: 'JH90' },
  { name: 'CYLINDER', category: 'CD70F' },
  { name: 'CYLINDER', category: 'CG125' },
  { name: 'CYLINDER 100CC', category: 'Qingqi 4-Stroke' },
  { name: 'CYLINDER 69mm', category: 'CG125 CDI' },
  { name: 'CYLINDER 78CC', category: 'Star' },
  { name: 'CYLINDER 78CC (ALUMINIUM)', category: 'Star' },
  { name: 'CYLINDER PACKING (GREEN)', category: 'CD70F' },
  { name: 'CYLINDER PACKING (GREEN)', category: 'CG125' },
  { name: 'D RUBBER', category: 'CD70F' },
  { name: 'DOWEL PIN SET', category: 'CD70F' },
  { name: 'DOWEL PIN SET', category: 'CG125' },
  { name: 'DRIVE PLATE', category: 'CD70F' },
  { name: 'DRUM BUSH SET', category: 'CG125' },
  { name: 'DRUM RUBBER', category: 'CD70F' },
  { name: 'ENGINE FOUNDATION LOWER WITH NUT', category: 'CD70 CDI' },
  { name: 'ENGINE FOUNDATION UPPER WITH NUT', category: 'CD70 CDI' },
  { name: 'ENGINE OIL (1000 ML) ULTRA BOOST (20W-50)', category: 'CG125' },
  { name: 'ENGINE OIL (700 ML) ULTRA BOOST (20W-50)', category: 'CD70F' },
  { name: 'ENGINE OIL (800 ML) ULTRA BOOST (20W-50)', category: 'CD100' },
  { name: 'ENGINE PIECE LEFT', category: 'CD70F' },
  { name: 'ENGINE PIECE RIGHT', category: 'CD70F' },
  { name: 'FENDER FRONT (BLACK)', category: 'CD70 Euro 2' },
  { name: 'FENDER FRONT (CHROME)', category: 'CD70 Euro 2' },
  { name: 'FENDER REAR (BLACK)', category: 'CD70 Euro 2' },
  { name: 'FENDER REAR (CHROME)', category: 'CD70 Euro 2' },
  { name: 'FINGER', category: 'CD70F' },
  { name: 'FLOAT BALL W/PIN', category: 'CD70 Euro 2' },
  { name: 'FLOAT BALL W/PIN', category: 'CD70F' },
  { name: 'FLOAT BALL W/PIN', category: 'CG125 CDI' },
  { name: 'FLOAT BALL W/PIN WITH STEEL CLIP', category: 'CD70 Euro 2' },
  { name: 'FLOAT PIN (NEEDLE VALVE)', category: 'CD70 Euro 2' },
  { name: 'FLOAT PIN (NEEDLE VALVE)', category: 'CD70F' },
  { name: 'FLOAT PIN (NEEDLE VALVE)', category: 'CG125' },
  { name: 'FOOT REST BAR', category: 'CD70 Euro 2' },
  { name: 'FOOT REST BAR WITH SIDE STAND', category: 'CD70 Euro 2' },
  { name: 'FOOT REST REAR (SET)', category: 'CD70 CDI' },
  { name: 'FOOT REST REAR (SET)', category: 'CG125' },
  { name: 'FOOT REST RUBBER (SET)', category: 'CD70 Euro 2' },
  { name: 'FOOT REST RUBBER (SET)', category: 'CD70F' },
  { name: 'FORK BUSH (CHIMTA BUSH)', category: 'CD70F' },
  { name: 'FORK BUSH (CHIMTA BUSH)', category: 'CG125' },
  { name: 'FRONT SHOCK BOTTOM SET (BOTTLE)', category: 'CD70 CDI' },
  { name: 'FRONT SHOCK BOTTOM SET (BOTTLE)', category: 'JH90' },
  { name: 'FRONT SHOCK GLASS BIG CHROME SET', category: 'CD70 CDI' },
  { name: 'FRONT SHOCK GLASS BIG CHROME SET', category: 'CG125' },
  { name: 'FRONT SHOCK GLASS BIG CHROME SET', category: 'JH90' },
  { name: 'FRONT SHOCK GLASS SMALL CHROME SET', category: 'CD70 CDI' },
  { name: 'FRONT SHOCK GLASS SMALL CHROME SET', category: 'CG125' },
  { name: 'FRONT SHOCK GLASS SMALL CHROME SET', category: 'JH90' },
  { name: 'FRONT SHOCK KAAN BLACK SET', category: 'CD70 CDI' },
  { name: 'FRONT SHOCK KAAN BLACK SET', category: 'CD70 Euro 2' },
  { name: 'FRONT SHOCK KAAN RED SET', category: 'CD70 CDI' },
  { name: 'FRONT SHOCK KAAN RED SET', category: 'CD70 Euro 2' },
  { name: 'FRONT SHOCK ROD (INNER TUBE)', category: 'CD70 CDI' },
  { name: 'FRONT SHOCK ROD (INNER TUBE)', category: 'JH90' },
  { name: 'FRONT SHOCK SPRING BIG SET', category: 'CD70 CDI' },
  { name: 'FRONT SHOCK SPRING SET', category: 'JH90' },
  { name: 'FRONT SPROCKET 14T', category: 'CD70F' },
  { name: 'FUEL COCK', category: 'CD70 CDI' },
  { name: 'FUEL COCK (CD70C)', category: 'Star' },
  { name: 'FUEL COCK WITH LOCK', category: 'CD70 CDI' },
  { name: 'FUEL TANK CAP', category: 'CD70F' },
  { name: 'FUEL TANK CAP', category: 'CG125 CDI' },
  { name: 'GASKET CLUTCH BOSS', category: 'CD70F' },
  { name: 'GASKET ENGINE PIECE GREEN', category: 'CD70F' },
  { name: 'GASKET FULL (GREEN)', category: 'CD70 CDI' },
  { name: 'GASKET FULL (GREEN)', category: 'CG125' },
  { name: 'GASKET FULL (GREEN)', category: 'Qingqi 4-Stroke' },
  { name: 'GASKET HALF (GREEN)', category: 'CD70 CDI' },
  { name: 'GASKET HALF (GREEN)', category: 'CG125' },
  { name: 'GASKET HALF (GREEN)', category: 'Qingqi 4-Stroke' },
  { name: 'GASKET TIMING COVER GREEN', category: 'CD70F' },
  { name: 'GASKET TOP COVER GREEN', category: 'CD70F' },
  { name: 'GEAR 23421', category: 'CD70F' },
  { name: 'GEAR 23431', category: 'CD70F' },
  { name: 'GEAR 23441', category: 'CD70F' },
  { name: 'GEAR 23451', category: 'CD70F' },
  { name: 'GEAR 23461 2 LEGS', category: 'CD70F' },
  { name: 'GEAR 23461 4 LEGS', category: 'CD70 CDI' },
  { name: 'GEAR 23471', category: 'CD70F' },
  { name: 'GEAR 23481', category: 'CD70F' },
  { name: 'GEAR BEARING 13.5x12', category: 'CD70F' },
  { name: 'GEAR BEARING 13.5x12', category: 'Star' },
  { name: 'GEAR BEARING 14x12', category: 'CD70F' },
  { name: 'GEAR BEARING 14x12', category: 'Star' },
  { name: 'GEAR CENTER PIECE 67T', category: 'CD70F' },
  { name: 'GEAR DRUM COMPLETE', category: 'CD70F' },
  { name: 'GEAR DRUM COMPLETE', category: 'Hero' },
  { name: 'GEAR DRUM WASHER', category: 'CD70F' },
  { name: 'GEAR INDICATOR INNER SWITCH', category: 'LF70' },
  { name: 'GEAR LEVER', category: 'CD70 CDI' },
  { name: 'GEAR LEVER', category: 'CG125 CDI' },
  { name: 'GEAR LEVER (CHROME)', category: 'United 100' },
  { name: 'GEAR LEVER (HONDA TYPE)', category: 'CD70 Euro 2' },
  { name: 'GEAR SHAFT COMPLETE', category: 'CD70F' },
  { name: 'GEAR SHAFT COMPLETE', category: 'CG125' },
  { name: 'GEAR SHAFT COMPLETE', category: 'United 100' },
  { name: 'GEAR SHAFT SPRING (SMALL)', category: 'CD70F' },
  { name: 'GEAR STAR', category: 'CD70F' },
  { name: 'GEAR WASHER KIT', category: 'CD70F' },
  { name: 'GEAR WASHER KIT', category: 'CG125' },
  { name: 'H/L BULB 12V 25X25W', category: 'CD70F' },
  { name: 'H/L BULB 12V 35X35W', category: 'CD70F' },
  { name: 'HANDLE BAR WITH BALANCER', category: 'CD70 CDI' },
  { name: 'HANDLE CONE SET', category: 'CD70F' },
  { name: 'HANDLE CONE SET (ROLLER BEARING TYPE)', category: 'CD70F' },
  { name: 'HANDLE GOLI SET (NYLON)', category: 'CD70F' },
  { name: 'HANDLE GRIP SET', category: 'CD70 CDI' },
  { name: 'HANDLE HOLDER SET', category: 'CD70F' },
  { name: 'HANDLE LOCK', category: 'CD70F' },
  { name: 'HANDLE NUT (CROME)', category: 'CD70F' },
  { name: 'HANDLE T BRIDGE PLATE', category: 'CG125' },
  { name: 'HANDLE T ONLY', category: 'CD70F' },
  { name: 'HANDLE T ONLY', category: 'CG125' },
  { name: 'HEAD COMPLETE', category: 'CD70F' },
  { name: 'HEAD COMPLETE', category: 'CG125' },
  { name: 'HEAD COMPLETE', category: 'Star' },
  { name: 'HEAD COMPLETE 2012 MODEL', category: 'CD70 Euro 2' },
  { name: 'HEAD GASKET (RED LINING)', category: 'CD70 CDI' },
  { name: 'HEAD GASKET (RED LINING)', category: 'CG125' },
  { name: 'HEAD GASKET (RED LINING)', category: 'Qingqi 4-Stroke' },
  { name: 'HEAD LIGHT CASE', category: 'CD70 CDI' },
  { name: 'HEAD LIGHT CASE', category: 'CG125' },
  { name: 'HEAD LIGHT COMPLETE WITH FIT BULB', category: 'CD70 CDI' },
  { name: 'HEAD LIGHT HOLDER', category: 'CD70F' },
  { name: 'HEAD LIGHT LENS (STAINLEY)', category: 'CD70 CDI' },
  { name: 'HEAD LIGHT ONLY WITH FIT BULB (WITHOUT CASE)', category: 'CD70 CDI' },
  { name: 'HEAD LIGHT REFLECTOR', category: 'CD70 CDI' },
  { name: 'HEAD LIGHT RIM CHROME', category: 'CD70 CDI' },
  { name: 'HOCKEY PATTI', category: 'CD70F' },
  { name: 'HOCKEY PATTI', category: 'Sohrab' },
  { name: 'HORN CROME 12V H-DUTY 100% COPPER', category: 'CD70F' },
  { name: 'IGNITION COIL 12V', category: 'CD70 Euro 2' },
  { name: 'IGNITION COIL 12V', category: 'CD70F' },
  { name: 'IGNITION COIL 12V', category: 'CG125 CDI' },
  { name: 'INDICATOR (2003)', category: 'CD70F' },
  { name: 'INDICATOR ASSY', category: 'CG125' },
  { name: 'INDICATOR FRONT LEFT', category: 'CD70 Euro 2' },
  { name: 'INDICATOR FRONT RIGHT', category: 'CD70 Euro 2' },
  { name: 'INDICATOR RUBBER', category: 'CD70 CDI' },
  { name: 'INDICATOR RUBBER', category: 'CD70 Euro 2' },
  { name: 'INSULATOR', category: 'CG125 CDI' },
  { name: 'INSULATOR (HONDA TYPE)', category: 'CG125 Euro 2' },
  { name: 'INSULATOR WITH ORING', category: 'CD70 CDI' },
  { name: 'JUMP RIB FRONT', category: 'CD70F' },
  { name: 'JUMP RIB FRONT', category: 'CG125' },
  { name: 'KEY SET', category: 'CD70F' },
  { name: 'KEY SET', category: 'CG125 CDI' },
  { name: 'KICK', category: 'C100' },
  { name: 'KICK', category: 'CD100' },
  { name: 'KICK', category: 'CD70 Euro 2' },
  { name: 'KICK (CROME)', category: 'CD70F' },
  { name: 'KICK', category: 'CG125 CDI' },
  { name: 'KICK SHAFT COMPLETE', category: 'CD70F' },
  { name: 'KICK SHAFT COMPLETE', category: 'CG125' },
  { name: 'KICK SHAFT COMPLETE', category: 'United 100' },
  { name: 'KICK SHAFT ONLY', category: 'CD70F' },
  { name: 'KICK SHAFT ONLY', category: 'CG125' },
  { name: 'KICK SHAFT ONLY', category: 'United 100' },
  { name: 'KICK SPRING', category: 'CD70F' },
  { name: 'KICK SPRING', category: 'CG125' },
  { name: 'LEVER ASSEMBLY SET BLACK (2010 MODEL)', category: 'CD70 Euro 2' },
  { name: 'LEVER ASSEMBLY SET BLACK 2012 MODEL', category: 'CG125 Euro 2' },
  { name: 'LEVER ASSY HALF LEFT ONLY BLACK (2010 MODEL)', category: 'CD70 Euro 2' },
  { name: 'LEVER ASSY HALF LEFT ONLY BLACK (2012 MODEL)', category: 'CG125 Euro 2' },
  { name: 'LEVER ASSY. LEFT ONLY BLACK (2010 MODEL)', category: 'CD70 Euro 2' },
  { name: 'LEVER ASSY. LEFT ONLY BLACK 2012 MODEL', category: 'CG125 Euro 2' },
  { name: 'LEVER BRAKE (R) BLACK', category: 'CD70 Euro 2' },
  { name: 'LEVER CLUTCH (L) BLACK', category: 'CD70 Euro 2' },
  { name: 'LEVER HOLDER BRAKE WITH SCREW 2010 MODEL', category: 'CD70 Euro 2' },
  { name: 'LEVER HOLDER LEFT LOWER 2010 MODEL', category: 'CD70 Euro 2' },
  { name: 'LEVER HOLDER RIGHT 2010 MODEL (THROTTLE HOLDER ONLY)', category: 'CD70 Euro 2' },
  { name: 'LIMITER PIPE (YELLOW)', category: 'CD70F' },
  { name: 'MAGNET COIL RING', category: 'CD70 CDI' },
  { name: 'MAGNET COIL RING', category: 'CG125 CDI' },
  { name: 'MAGNET COIL RING', category: 'Hero' },
  { name: 'MAGNET COIL RING', category: 'United 100' },
  { name: 'MAGNET COIL RING LEED', category: 'CD70 CDI' },
  { name: 'MAGNET COMPLETE', category: 'CD70 CDI' },
  { name: 'MAGNET COMPLETE', category: 'CG125 CDI' },
  { name: 'MAGNET COMPLETE (HERO)', category: 'Hero' },
  { name: 'MAGNET ORING KIT', category: 'CD70F' },
  { name: 'MAGNET ORING KIT W/OIL SEAL', category: 'CD70F' },
  { name: 'MAGNET ORING KIT W/OIL SEAL (05 PCS)', category: 'CG125 Euro 2' },
  { name: 'MAGNET ORING KIT W/OIL SEAL (08 PCS)', category: 'CG125 Euro 2' },
  { name: 'MAGNET PLATE ONLY', category: 'CD70 CDI' },
  { name: 'MAGNET PLATE ONLY', category: 'CG125 CDI' },
  { name: 'MAGNET PLATE ONLY', category: 'Hero' },
  { name: 'MAIN JET # 72', category: 'CD70F' },
  { name: 'MAIN JET # 75', category: 'CD70F' },
  { name: 'MAIN JET # 78', category: 'CD70F' },
  { name: 'MAIN SHAFT', category: 'CD70F' },
  { name: 'MAIN STAND', category: 'CD70 CDI' },
  { name: 'MAIN STAND', category: 'CD70 Euro 2' },
  { name: 'METER CABLE', category: 'CD70F' },
  { name: 'METER CABLE 2007 MODEL', category: 'CG125 CDI' },
  { name: 'METER CABLE 2012 MODEL', category: 'CD70 Euro 2' },
  { name: 'METER CABLE 2015 MODEL', category: 'CG125 Euro 2' },
  { name: 'METER COMPLETE', category: 'CD70 Euro 2' },
  { name: 'METER COMPLETE', category: 'CG125 Euro 2' },
  { name: 'METER COMPLETE (2006 MODEL)', category: 'CD70 CDI' },
  { name: 'METER COVER', category: 'CG125 Euro 2' },
  { name: 'METER COVER (2006 MODEL)', category: 'CD70 CDI' },
  { name: 'METER GEAR SET', category: 'CD100' },
  { name: 'METER GEAR SET', category: 'CD70F' },
  { name: 'METER GEAR SET (2013 MODEL)', category: 'CD70 Euro 2' },
  { name: 'METER GEAR SET (METAL)', category: 'CD70 Euro 2' },
  { name: 'METER GEAR SET W/BUSH (JH-70)', category: 'CD70F' },
  { name: 'METER MOVEMENT W/NEELDE', category: 'CD70 CDI' },
  { name: 'MIXTURE SCREW KIT', category: 'CD70 Euro 2' },
  { name: 'MIXTURE SCREW KIT', category: 'CD70F' },
  { name: 'MIXTURE SCREW KIT', category: 'CG125' },
  { name: 'MIXTURE SCREW KIT', category: 'CG125 Euro 2' },
  { name: 'MUFFLER ASSY', category: 'CD70F' },
  { name: 'MUFFLER ASSY (CHROME)', category: 'CD70 Euro 2' },
  { name: 'MUFFLER BEND', category: 'CD70F' },
  { name: 'MUFFLER BRACKET', category: 'CD70 CDI' },
  { name: 'MUFFLER WASHER (COPPER)', category: 'CD70F' },
  { name: 'NEUTRAL SWITCH', category: 'CD70F' },
  { name: 'NEUTRAL SWITCH WITH WIRE', category: 'Star' },
  { name: 'OIL BOLT CROME W/WASHER', category: 'CD70F' },
  { name: 'OIL GUAGE (CROME)', category: 'CD70F' },
  { name: 'OIL GUAGE (CROME)', category: 'CG125' },
  { name: 'OIL PUMP COMPLETE', category: 'CD100' },
  { name: 'OIL PUMP COMPLETE', category: 'CD70 CDI' },
  { name: 'OIL PUMP COMPLETE', category: 'CG125' },
  { name: 'OIL PUMP COMPLETE', category: 'Star' },
  { name: 'OIL PUMP COMPLETE (PREMIUM QUALITY)', category: 'CD100' },
  { name: 'OIL PUMP COMPLETE (PREMIUM QUALITY)', category: 'CD70 CDI' },
  { name: 'OIL PUMP COMPLETE (PREMIUM QUALITY)', category: 'Star' },
  { name: 'OIL PUMP GEAR EASY FIT', category: 'CD70F' },
  { name: 'OIL PUMP JALI', category: 'CD70F' },
  { name: 'OIL PUMP JALI', category: 'CG125' },
  { name: 'OIL PUMP KUPPA', category: 'CG125' },
  { name: 'OIL PUMP ROD', category: 'CD70F' },
  { name: 'OIL PUMP ROD WITH BUSH', category: 'CD70F' },
  { name: 'OIL SEAL KIT', category: 'CD70F' },
  { name: 'OIL THROUGH KIT', category: 'CD70F' },
  { name: 'OIL THROUGH KIT', category: 'United 100' },
  { name: 'PETROL PIPE 160MM (1BOX = 20 PCS)', category: 'CD70F' },
  { name: 'PISTON KIT 0.50', category: 'CD70F' },
  { name: 'PISTON KIT 0.50', category: 'CG125' },
  { name: 'PISTON KIT 0.50', category: 'CG125 Euro 2' },
  { name: 'PISTON KIT 0.50', category: 'Qingqi 4-Stroke' },
  { name: 'PISTON KIT 0.50', category: 'Sohrab' },
  { name: 'PISTON KIT 1.00', category: 'CD70F' },
  { name: 'PISTON KIT 1.00', category: 'CG125' },
  { name: 'PISTON KIT 1.00', category: 'CG125 Euro 2' },
  { name: 'PISTON KIT 1.00', category: 'Qingqi 4-Stroke' },
  { name: 'PISTON KIT 1.00', category: 'Sohrab' },
  { name: 'PISTON KIT 1.50', category: 'CD70F' },
  { name: 'PISTON KIT 1.50', category: 'CG125' },
  { name: 'PISTON KIT 1.50', category: 'Qingqi 4-Stroke' },
  { name: 'PISTON KIT 1.50', category: 'Sohrab' },
  { name: 'PISTON KIT STD', category: 'CD70F' },
  { name: 'PISTON KIT STD', category: 'CG125' },
  { name: 'PISTON KIT STD', category: 'CG125 Euro 2' },
  { name: 'PISTON KIT STD', category: 'Qingqi 4-Stroke' },
  { name: 'PISTON KIT STD', category: 'Sohrab' },
  { name: 'PISTON RING SET 0.50', category: 'CD70F' },
  { name: 'PISTON RING SET 0.50', category: 'CG125' },
  { name: 'PISTON RING SET 0.50', category: 'Qingqi 4-Stroke' },
  { name: 'PISTON RING SET 1.00', category: 'CD70F' },
  { name: 'PISTON RING SET 1.00', category: 'CG125' },
  { name: 'PISTON RING SET 1.00', category: 'Qingqi 4-Stroke' },
  { name: 'PISTON RING SET 1.50', category: 'CD70F' },
  { name: 'PISTON RING SET 1.50', category: 'CG125' },
  { name: 'PISTON RING SET 1.50', category: 'Qingqi 4-Stroke' },
  { name: 'PISTON RING SET STD', category: 'CD70F' },
  { name: 'PISTON RING SET STD', category: 'CG125' },
  { name: 'PISTON RING SET STD', category: 'Qingqi 4-Stroke' },
  { name: 'PLUG C7HSA', category: 'CD70F' },
  { name: 'PLUG CAP (BLACK)', category: 'CD70F' },
  { name: 'PLUG CAP (STEEL)', category: 'CD70F' },
  { name: 'PLUG CAP BLACK (WATER PROOF)', category: 'CD70F' },
  { name: 'PLUG DP8EA-9', category: 'CG125' },
  { name: 'PRESSURE PLATE', category: 'CD70F' },
  { name: 'PRESSURE PLATE', category: 'CG125' },
  { name: 'PRESSURE PLATE', category: 'Qingqi 4-Stroke' },
  { name: 'PRESSURE PLATE', category: 'United 100' },
  { name: 'PULSAR COIL', category: 'CD70 CDI' },
  { name: 'PULSAR COIL', category: 'Hero' },
  { name: 'PUSH ROD', category: 'CG125' },
  { name: 'PUSH ROD (BLACK)', category: 'CG125 CDI' },
  { name: 'PUSH RUBBER', category: 'CD70F' },
  { name: 'R.P.M CABLE', category: 'CG125' },
  { name: 'R.P.M. GEAR', category: 'CG125' },
  { name: 'REAR FORK (BLACK) (CHIMTA) WITH BUSH', category: 'CD70 CDI' },
  { name: 'REAR SHOCK SPRING (SET)', category: 'CD70 CDI' },
  { name: 'REAR SHOCK SPRING SET', category: 'JH90' },
  { name: 'RECTIFIER 12V', category: 'CD70 Euro 2' },
  { name: 'RECTIFIER 12V', category: 'CD70F' },
  { name: 'RECTIFIER 12V (TRANSPARENT)', category: 'CD70F' },
  { name: 'RECTIFIER LEED', category: 'CD70 CDI' },
  { name: 'ROCKER PIN', category: 'CG125' },
  { name: 'ROCKER PIN (2PC/SET)', category: 'CD70F' },
  { name: 'ROCKER PIN WASHER', category: 'CG125' },
  { name: 'ROCKER PLATE', category: 'CG125' },
  { name: 'ROCKER PLATE', category: 'CG125 Euro 2' },
  { name: 'ROCKER W/BEARING & TAPPET SCREW', category: 'CD70 CDI' },
  { name: 'ROCKER W/TAPPET NUT BOLT', category: 'CD70F' },
  { name: 'ROCKER W/TAPPET NUT BOLT', category: 'CG125 Euro 2' },
  { name: 'ROLLER BOLT (CROME) WITH WASHER', category: 'CD70F' },
  { name: 'ROLLER RUBBER ONLY WITHOUT BUSH', category: 'CD70F' },
  { name: 'ROLLER RUBBER ONLY WITHOUT BUSH', category: 'United 100' },
  { name: 'ROLLER TENSIONER SET WITHOUT BUSH', category: 'CD70F' },
  { name: 'ROLLER TENSIONER SET WITHOUT BUSH', category: 'United 100' },
  { name: 'SEAT ASSY DOUBLE', category: 'CD70 CDI' },
  { name: 'SEAT ASSY. DOUBLE', category: 'CD70 Euro 2' },
  { name: 'SEAT COWL (BLACK) SET', category: 'CD70 CDI' },
  { name: 'SEAT COWL (RED SET)', category: 'CD70 Euro 2' },
  { name: 'SEAT COWL (RED) SET', category: 'CD70 CDI' },
  { name: 'SEAT PIPE ASSY WITH BRACKET', category: 'CD70 CDI' },
  { name: 'SHOCK PUMP REAR SET', category: 'CD70 CDI' },
  { name: 'SHOCK PUMP REAR SET', category: 'JH90' },
  { name: 'REAR SHOCK', category: 'CG125' },
  { name: 'SHOCK REAR BLACK H/D', category: 'CD70F' },
  { name: 'SHOCK REAR RED H/D', category: 'CD70F' },
  { name: 'SHOCK SEAL (DOUBLE SPRING) 27X37X10.5', category: 'JH90' },
  { name: 'SHOCK SEAL 25X35X9', category: 'CD70F' },
  { name: 'SHOCK SEAL 27X39X10.5', category: 'CG125' },
  { name: 'SIDE COVER SET L & R (BLACK SET)', category: 'CD70 CDI' },
  { name: 'SIDE STAND', category: 'CD70 Euro 2' },
  { name: 'SIDE STAND', category: 'CD70F' },
  { name: 'SLIDE PIN JET', category: 'CD70 CDI' },
  { name: 'SLIDE PIN JET', category: 'CD70 Euro 2' },
  { name: 'SLIDE PIN JET', category: 'CD70F' },
  { name: 'SLIDE PIN JET', category: 'CG125 CDI' },
  { name: 'SLIDE PIN JET', category: 'CG125 Euro 2' },
  { name: 'SLOW JET 35#', category: 'CD70F' },
  { name: 'SOUND FLASHER 12V', category: 'CD70F' },
  { name: 'SPROCKET BOLT KIT (CROME)', category: 'CG125' },
  { name: 'SPROCKET BOLT KIT (GOLDEN)', category: 'CG125' },
  { name: 'SPROCKET BOLT KIT GALVANIZE', category: 'CD70F' },
  { name: 'SPROCKET LOCK 14T', category: 'CD70F' },
  { name: 'SPROCKET PANNEL', category: 'CD70F' },
  { name: 'STUD', category: 'CD70F' },
  { name: 'STUD', category: 'CG125' },
  { name: 'STUD', category: 'Star' },
  { name: 'SWITCH', category: 'CD100' },
  { name: 'SWITCH', category: 'CD70F' },
  { name: 'SWITCH', category: 'CG125 CDI' },
  { name: 'SWITCH', category: 'Hero' },
  { name: 'SWITCH KIT', category: 'CD70F' },
  { name: 'SWITCH KIT', category: 'CG125 CDI' },
  { name: 'TAPPET COVER (CROME)', category: 'CD70F' },
  { name: 'TAPPET COVER (CROME)', category: 'CG125' },
  { name: 'TAPPET NUT & BOLT', category: 'CD70F' },
  { name: 'TAPPET NUT & BOLT', category: 'CG125' },
  { name: 'TENSIONER PATTI', category: 'CD70 Euro 2' },
  { name: 'TENSIONER PATTI', category: 'CD70F' },
  { name: 'THROTTLE CABLE', category: 'CD70 CDI' },
  { name: 'THROTTLE CABLE', category: 'CG125' },
  { name: 'THROTTLE CABLE', category: 'CG125 Euro 2' },
  { name: 'THROTTLE CABLE 64 MM', category: 'CD70 Euro 2' },
  { name: 'TIMING CHAIN 82L', category: 'CD70F' },
  { name: 'TIMING CHAIN 84L', category: 'Sohrab' },
  { name: 'TIMING CHAIN KIT 82L', category: 'CD70F' },
  { name: 'TIMING CHAIN KIT 84L', category: 'Sohrab' },
  { name: 'TIMING COVER', category: 'CD70F' },
  { name: 'TIMING GEAR', category: 'CD70 CDI' },
  { name: 'TIMING GEAR', category: 'Sohrab' },
  { name: 'TIMING GEAR (2012 MODEL)', category: 'CD70 Euro 2' },
  { name: 'TIMING ROD W/PUSH RUBBER', category: 'CD70F' },
  { name: 'TIMING ROD W/PUSH RUBBER & SPRING', category: 'CD70F' },
  { name: 'TIMING SPRING', category: 'CD70F' },
  { name: 'TOP COVER (BLACK)', category: 'CG125' },
  { name: 'TOP COVER (HEAD)', category: 'CD70F' },
  { name: 'TOP COVER ORING', category: 'CG125' },
  { name: 'TRANSMISSION ASSY. COMPLETE', category: 'CD70F' },
  { name: 'TRANSMISSION ASSY. COMPLETE', category: 'CG125' },
  { name: 'TRANSMISSION ASSY. COMPLETE', category: 'United 100' },
  { name: 'VALVE CAP', category: 'CD70F' },
  { name: 'VALVE COTTER', category: 'CD70F' },
  { name: 'VALVE COTTER', category: 'CG125' },
  { name: 'VALVE COTTER', category: 'CG125 CDI' },
  { name: 'VALVE COTTER', category: 'Sohrab' },
  { name: 'VALVE SEAL', category: 'CD70F' },
  { name: 'VALVE SEAL', category: 'CG125' },
  { name: 'VALVE SEAL', category: 'Sohrab' },
  { name: 'VALVE SET', category: 'CD70F' },
  { name: 'VALVE SET', category: 'CG125 CDI' },
  { name: 'VALVE SET', category: 'Sohrab' },
  { name: 'VALVE SET OVER SIZE', category: 'CD70F' },
  { name: 'VALVE SET OVER SIZE', category: 'CG125 CDI' },
  { name: 'VALVE SET OVER SIZE', category: 'Sohrab' },
  { name: 'VALVE SPRING SET', category: 'CD70F' },
  { name: 'VALVE SPRING SET', category: 'CG125' },
  { name: 'VALVE SPRING SET', category: 'Sohrab' },
  { name: 'WEIGHT COLLAR', category: 'CD70F' },
  { name: 'WHEEL DRUM FRONT', category: 'CD70F' },
  { name: 'WHEEL DRUM REAR', category: 'CD70F' },
  { name: 'WHEEL DRUM REAR', category: 'CG125' },
  { name: 'WHEEL RIM SET (2.25X17/2.50X17)', category: 'CD70 CDI' },
  { name: 'WHEEL SLEEVE', category: 'CD70F' },
  { name: 'WIRING', category: 'CD70 CDI' },
  { name: 'WIRING', category: 'CD70 Euro 2' },
  { name: 'WIRING', category: 'CG125 CDI' },
  { name: 'WIRING', category: 'Star' },
  { name: 'WIRING "HEAVY DUTY"', category: 'CD70 CDI' },
  { name: 'WIRING "HEAVY DUTY"', category: 'CD70 Euro 2' },
  { name: 'WIRING "HEAVY DUTY"', category: 'CG125 CDI' },
  { name: 'WIRING "HEAVY DUTY"', category: 'Star' },
  {
    name: 'Battery Dry Cell',
    category: 'Universal / Generic Parts',
    variants: [{ size: '12V 2.5 AH' }, { size: '12V 5 AH' }],
  },
  {
    name: 'Bearing',
    category: 'Universal / Generic Parts',
    variants: [
      { size: '6000' },
      { size: '6001' },
      { size: '6202' },
      { size: '6203' },
      { size: '6205' },
      { size: '6300' },
      { size: '6301' },
      { size: '6302' },
      { size: '6304 A (CJB)' },
      { size: '6328 A (CJB)' },
    ],
  },
  {
    name: 'Chain Lock',
    category: 'Universal / Generic Parts',
    variants: [
      { size: '420' },
      { size: '420H (HEAVY DUTY)' },
      { size: '428' },
      { size: '428H (HEAVY DUTY)' },
    ],
  },
  {
    name: 'Oil Seal',
    category: 'Universal / Generic Parts',
    variants: [
      { size: '11X6X24X10' },
      { size: '12X21X4' },
      { size: '13X8X24X5' },
      { size: '17X29X5' },
      { size: '18X9X30X5' },
      { size: '21X35X7 (FRONT HUB)' },
      { size: '22X35X7' },
    ],
  },
  {
    name: 'Spoke',
    category: 'Universal / Generic Parts',
    variants: [
      { size: 'BUTTED 2.25X17' },
      { size: 'BUTTED 2.50X17' },
      { size: 'BUTTED 2.50X18' },
      { size: 'BUTTED 3.00X17' },
      { size: 'STRAIGHT 3.00X17 (BIG NIPPLE)' },
    ],
  },
  {
    name: 'Tyre Sealant',
    category: 'Universal / Generic Parts',
    variants: [{ size: '250 ML' }, { size: '450 ML' }],
  },
  {
    name: 'Wheel Chain',
    category: 'Universal / Generic Parts',
    variants: [{ size: '420X104L' }, { size: '420X104L W/O BOX' }, { size: '428X100L' }],
  },
  { name: 'FUEL FILTER', category: 'Universal / Generic Parts' },
  { name: 'INDICATOR (SPECIAL)', category: 'Universal / Generic Parts' },
];

// Totals: 558 model-specific products + 7 universal families (33 variants) + 2 standalone universal products = 567 products, 18 categories.
